### ISSUE TITLE
Auto Layout

### ISSUE THREAD

**Issue by d3020** [ShengHuaWu/ValueTypeForUI#1]
This isn't an issue, but I was curious on your response. How do you feel about this... There seems to be so, so much code here that is needed to do this layout. Compared to just say using VFL in code for an example like this, plus you'd have auto layout. Whereas here when you rotate, there is no accommodating for the orientation. 

I'm just not seeing benefits. Can you explain maybe? Thanks.

**Comment by ShengHuaWu** [comment]
Hi @d3020,

I'm sorry for late reply.

Perhaps, I chose a bad example to demonstrate this technique.
My point is we can separate our layout into different tiny `structs` and reunite them to display the layout. Moreover, it's possible to reuse these `structs` through our project as well.
In a nutshell, this technique is another layout abstraction just like `AutoLayout`.
However, you're right. This technique will complicate the codebase if the layout is quite simple.

`AutoLayout` has benefits when developing a simple layout, especially after Apple released `NSLayoutAnchor` in iOS 9. However, Developing a complex layout with `AutoLayout` will impact app's performance. (Linkedin released [LayoutKit](https://engineering.linkedin.com/blog/2016/06/open-sourcing-layoutkit--a-fast-view-layout-library-for-ios-appl) to resolve the performance issue.) In my personal experience, `AutoLayout` isn't animation friendly if I don't want the default animation effect.

I'm not saying that everyone should avoid `Autolayout`. It's really important to choose the appropriate tool for the task. Thank you for asking this question.
